name: AI-24
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20211102.0
  - absl-py=1.4.0
  - aiofiles=22.1.0
  - aiohttp=3.10.5
  - aiosignal=1.2.0
  - aiosqlite=0.18.0
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0=mkl
  - bleach=4.1.0
  - blinker=1.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.7.2
  - cachetools=4.2.2
  - certifi=2024.8.30
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.2.0
  - cryptography=43.0.0
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - expat=2.5.0
  - ffmpeg=4.3
  - fontconfig=2.14.2
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.4.0
  - giflib=5.2.1
  - glib=2.69.1
  - google-auth=2.22.0
  - google-auth-oauthlib=0.5.2
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.2.0
  - intel-openmp=2023.1.0
  - ipykernel=6.25.0
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.5
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.6.3
  - jupyter_server=2.10.0
  - jupyter_server_fileid=0.9.0
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.10
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.17
  - libevent=2.1.12
  - libffi=3.4.4
  - libiconv=1.17
  - libllvm14=14.0.6
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libsqlite=3.43.0
  - libtiff=4.5.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - lxml=5.2.1  
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - multidict=6.0.4
  - munkres=1.1.4
  - nb_conda=2.2.1
  - nb_conda_kernels=2.3.1
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.3
  - nbformat=5.9.2
  - nest-asyncio=1.5.6
  - nltk=3.8.1
  - notebook=6.5.7
  - notebook-shim=0.2.2
  - numpy=1.26.4
  - numpy-base=1.26.4
  - oauthlib=3.2.2
  - openssl=3.1.2
  - packaging=23.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - protobuf=3.20.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pygments=2.18.0
  - pyjwt=2.9.0
  - pyopenssl=24.2.1
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyrsistent=0.20.0
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - pytz=2024.2
  - pytorch=1.12.1  
  - torchvision=0.13.1 